spring.application.name=internship
server.port = 9090
spring.config.import=optional:file:/c/temp/vault/pdf-config
logging.level.org.springframework.boot.context.config=DEBUG
spring.cloud.compatibility-verifier.enabled=false

spring.cloud.vault.uri=http://127.0.0.1:8200
spring.cloud.vault.token=root
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.application-name=myapp

logging.level.org.springframework.vault=DEBUG
