##spring.application.name=internship
server.port = 9090
spring.application.name=myapp

#spring.config.import=optional:vault://
spring.config.import=vault://

spring.cloud.vault.uri=http://127.0.0.1:8200
spring.cloud.vault.scheme=http
spring.cloud.vault.host=127.0.0.1
spring.cloud.vault.port=8200
###Enable this to test
###spring.cloud.vault.token=<use_ur_token_here>
spring.cloud.vault.ssl.enabled=false
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.default-context=myapp

logging.level.org.springframework.cloud.vault=DEBUG

